# autor: Jan Ostatnický xostatj00

all:
	mvn install
	mvn compile
	mvn package
	mvn javadoc:javadoc
	mvn javafx:run

clean:
	mvn clean

install:
	mvn install

build:
	mvn compile

package:
	mvn package

javadoc:
	mvn javadoc:javadoc

run:
	mvn javafx:run
