# autor: Jan Ostatnický xostatj00

all:
	mvn install
	mvn compile
	mvn package
	mvn javadoc:javadoc
	mvn exec:java -Dexec.args="15"

clean:
	mvn clean

install:
	mvn install

build:
	mvn compile

package:
	mvn package

javadoc:
	mvn javadoc:javadoc

easy:
	mvn exec:java -Dexec.args="5"

medium:
	mvn exec:java -Dexec.args="10"

hard:
	mvn exec:java -Dexec.args="15"

advanced:
	mvn exec:java -Dexec.args="20"

expert:
	mvn exec:java -Dexec.args="30"
